-- Obsidian BlackList Data
-- This file contains the shared blacklist data for the Obsidian addon.

Obsidian_External_Blacklist = {
	["flaggedPlayers"] = {
    ["kephtis"] = { ["name"] = "Kephtis", ["reason"] = "hosts AQ20 pulls pack vanishes and blames raid", ["dateadded"] = "040924", ["status"] = "medium", ["level"] = "??" },
    ["ivvraith"] = { ["name"] = "Ivvraith", ["reason"] = "hopes ppl get raped because he didnt understand SRing", ["dateadded"] = "300825", ["status"] = "medium", ["level"] = "??" },
    ["kallitsisbro"] = { ["name"] = "Kallitsisbro", ["reason"] = "calls ppl pedos and hates trannies", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["chimichuri"] = { ["name"] = "Chimichuri", ["reason"] = "crazy dude with mic and entitld twat", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["narghul"] = { ["name"] = "Narghul", ["reason"] = "wants to HR shit and gets angry", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["thirtyseven"] = { ["name"] = "Thirtyseven", ["reason"] = "leaves after getting his SR", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["havlak"] = { ["name"] = "Havlak", ["reason"] = "wanker", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["shandras"] = { ["name"] = "Shandras", ["reason"] = "Lootgoblin", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["chloverine"] = { ["name"] = "Chloverine", ["reason"] = "Rude in chat towards guildie", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["realzoe"] = { ["name"] = "Realzoe", ["reason"] = "very rude in chat towards guildie", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["deadcast"] = { ["name"] = "Deadcast", ["reason"] = "ninjalooter", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["bonethugsn"] = { ["name"] = "Bonethugsn", ["reason"] = "insults and rages after loosing", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["lendrill"] = { ["name"] = "Lendrill", ["reason"] = "ganks, gets counterganked and throws slurs", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["ezekilus"] = { ["name"] = "Ezekilus", ["reason"] = "trolls raid with giving idea", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["pescatorian"] = { ["name"] = "Pescatorian", ["reason"] = "joins afk and rolls on everything", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["ravengaar"] = { ["name"] = "Ravengaar", ["reason"] = "made raid, got his loot and left", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["smashsmashaa"] = { ["name"] = "Smashsmashaa", ["reason"] = "griefing a Silithus Lords group", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["puppasan"] = { ["name"] = "Puppasan", ["reason"] = "pulled garr and left the raid to troll", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["milfen"] = { ["name"] = "Milfen", ["reason"] = "left ZG run after Raptor mount didnt drop", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["wiggzadin"] = { ["name"] = "Wiggzadin", ["reason"] = "ninjas item and goes offline", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["loiter"] = { ["name"] = "Loiter", ["reason"] = "ragequit in scholo because tank pulls extra pack", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["xalithar"] = { ["name"] = "Xalithar", ["reason"] = "ever buffs, never decurses, goes afk mid fights", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["gabrindril"] = { ["name"] = "Gabrindril", ["reason"] = "takes OS items, tmog and DE item in ZG", ["dateadded"] = "170625", ["status"] = "medium", ["level"] = "??" },
    ["zeroero"] = { ["name"] = "Zeroero", ["reason"] = "ninjas alchemy recipe", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["murre"] = { ["name"] = "Murre", ["reason"] = "everything is MS on everything like a moron", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["deciofreitas"] = { ["name"] = "Deciofreitas", ["reason"] = "needs on a fucking healing robe in ES", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["kashune"] = { ["name"] = "Kashune", ["reason"] = "ninjalooted a cloth helmet", ["dateadded"] = "260226", ["status"] = "medium", ["level"] = "??" },
    ["paranoid"] = { ["name"] = "Paranoid", ["reason"] = "ninjaed dethbringer from Onyxia", ["dateadded"] = "061224", ["status"] = "medium", ["level"] = "??" },
    ["veknila"] = { ["name"] = "Veknila", ["reason"] = "Ninjaed item from AQ20", ["dateadded"] = "011224", ["status"] = "medium", ["level"] = "??" },
    ["airin"] = { ["name"] = "Airin", ["reason"] = "not healing and throws hit at TSC", ["dateadded"] = "241124", ["status"] = "medium", ["level"] = "??" },
    ["tulayne"] = { ["name"] = "Tulayne", ["reason"] = "Harressing raindog", ["dateadded"] = "151024", ["status"] = "medium", ["level"] = "??" },
    ["rundfur"] = { ["name"] = "Rundfur", ["reason"] = "flames vala", ["dateadded"] = "290924", ["status"] = "medium", ["level"] = "??" },
    ["arradiel"] = { ["name"] = "Arradiel", ["reason"] = "ganks griefs and then flips when countered", ["dateadded"] = "220924", ["status"] = "medium", ["level"] = "??" },
    ["holehhawg"] = { ["name"] = "Holehhawg", ["reason"] = "throws shit at guildie in chat", ["dateadded"] = "080924", ["status"] = "medium", ["level"] = "??" },
    ["worca"] = { ["name"] = "Worca", ["reason"] = "nutjob victimmentality", ["dateadded"] = "010924", ["status"] = "medium", ["level"] = "??" },
    ["alliecakes"] = { ["name"] = "Alliecakes", ["reason"] = "yeeted from guild due to drama stirring", ["dateadded"] = "010924", ["status"] = "medium", ["level"] = "??" },
    ["monti"] = { ["name"] = "Monti", ["reason"] = "yeeted from guild due to drama stirring", ["dateadded"] = "010924", ["status"] = "medium", ["level"] = "??" },
    ["harza"] = { ["name"] = "Harza", ["reason"] = "changed SR during raid after first SR didnt dorp", ["dateadded"] = "300824", ["status"] = "medium", ["level"] = "??" },
    ["dessert"] = { ["name"] = "Dessert", ["reason"] = "bails after his SR does not drop", ["dateadded"] = "170824", ["status"] = "medium", ["level"] = "??" },
    ["accelerator"] = { ["name"] = "Accelerator", ["reason"] = "kicked from guild because he was very annoying", ["dateadded"] = "160824", ["status"] = "medium", ["level"] = "??" },
    ["hotdruid"] = { ["name"] = "Hotdruid", ["reason"] = "refused to heal on UBRS because of master looter", ["dateadded"] = "090824", ["status"] = "medium", ["level"] = "??" },
    ["goblinwood"] = { ["name"] = "Goblinwood", ["reason"] = "calls us a bunch of twats", ["dateadded"] = "020724", ["status"] = "medium", ["level"] = "??" },
    ["frost"] = { ["name"] = "Frost", ["reason"] = "throws shit at TSC", ["dateadded"] = "030724", ["status"] = "medium", ["level"] = "??" },
    ["boutablow"] = { ["name"] = "Boutablow", ["reason"] = "raids gbank", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["imgonnagoob"] = { ["name"] = "Imgonnagoob", ["reason"] = "raided gbank in fika", ["dateadded"] = "010104", ["status"] = "medium", ["level"] = "??" },
    ["crommson"] = { ["name"] = "Crommson", ["reason"] = "host MC pug, wipes and leaves", ["dateadded"] = "180624", ["status"] = "medium", ["level"] = "??" },
    ["doomshock"] = { ["name"] = "Doomshock", ["reason"] = "goes crazy after being benched from K40", ["dateadded"] = "300524", ["status"] = "medium", ["level"] = "??" },
    ["keroin"] = { ["name"] = "Keroin", ["reason"] = "joins wants MoM rages and leaves", ["dateadded"] = "160524", ["status"] = "medium", ["level"] = "??" },
    ["garroshh"] = { ["name"] = "Garroshh", ["reason"] = "shit in AQ40 and bails guild", ["dateadded"] = "250424", ["status"] = "medium", ["level"] = "??" },
    ["shadowclaw"] = { ["name"] = "Shadowclaw", ["reason"] = "tank who dont listen and wipes 5 times in Q20 then leaves", ["dateadded"] = "280925", ["status"] = "medium", ["level"] = "??" },
    ["hadezlina"] = { ["name"] = "Hadezlina", ["reason"] = "clueless RL who just yells at ppli instead of actually raidleading", ["dateadded"] = "280925", ["status"] = "medium", ["level"] = "??" },
    ["gozrion"] = { ["name"] = "Gozrion", ["reason"] = "looses a picking off a dreamfoil", ["dateadded"] = "260925", ["status"] = "medium", ["level"] = "??" },
    ["myshu"] = { ["name"] = "Myshu", ["reason"] = "need rolls and goobs chests in kara halls", ["dateadded"] = "021225", ["status"] = "high", ["level"] = "??" },
    ["oxhnor"] = { ["name"] = "Oxhnor", ["reason"] = "asspulls in k10 wipes and leaves us", ["dateadded"] = "201225", ["status"] = "high", ["level"] = "??" },
    ["dashaoye"] = { ["name"] = "Dashaoye", ["reason"] = "queues for Strat live as healer, gets Medivh's feather, leaves", ["dateadded"] = "301225", ["status"] = "medium", ["level"] = "??" },
    ["aldebarran"] = { ["name"] = "Aldebarran", ["reason"] = "do only 2 thing ninja pull+ ninja loot and dont do anydamage", ["dateadded"] = "281225", ["status"] = "medium", ["level"] = "??" },
    ["voreon"] = { ["name"] = "Voreon", ["reason"] = "invites people to a pug, doesnt say anything about having SR+ and proceeds to kick when u ask about it", ["dateadded"] = "151225", ["status"] = "high", ["level"] = "??" },
    ["olinsonsship"] = { ["name"] = "Olinsonsship", ["reason"] = "petty camping of mob because he lost tag while mobtagging", ["dateadded"] = "091225", ["status"] = "low", ["level"] = "??" },
    ["jiara"] = { ["name"] = "Jiara", ["reason"] = "cancerous to play with. random sheep pulls when everyone is still moving. trying to give \"tips\" on how to play", ["dateadded"] = "041225", ["status"] = "low", ["level"] = "??" },
    ["cringeindeed"] = { ["name"] = "Cringeindeed", ["reason"] = "Demands stuff, kicks ppl form K10 for not getting it", ["dateadded"] = "231125", ["status"] = "medium", ["level"] = "??" },
    ["willynilly"] = { ["name"] = "Willynilly", ["reason"] = "Asshole to guild in raids and raids guildbank for items", ["dateadded"] = "121225", ["status"] = "high", ["level"] = "??" },
    ["xristos"] = { ["name"] = "Xristos", ["reason"] = "Aguy legit rolls on stuff he doesnt need and than tries to sell mid raid \"ohh if someone wants ill sell for 20g\" after people actually needed the item", ["dateadded"] = "111025", ["status"] = "high", ["level"] = "??" },
	},
}
